urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import login, logout

#from tastypie.api import Api
#from geddit.api.resources import UserResource, ItemResource, ClaimResource, CategoryResource, ReservationResource
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import settings

admin.autodiscover()

'''
v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(ClaimResource())
v1_api.register(ItemResource())
v1_api.register(CategoryResource())
v1_api.register(ReservationResource())
'''

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'geddit.views.home', name='home'),
    # url(r'^geddit/', include('geddit.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),


    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^jstest/', 'jstest.views.index'),
    #url(r'^api/', include(v1_api.urls)),
    url(r'^$', 'data.views.buy_page'),

    url(r'^buy$', 'data.views.buy_page'),
    url(r'^sell$', 'data.views.sell_page'),
    url(r'^dashboard$', 'data.views.dashboard_page'),
    url(r'^settings$', 'data.views.settings_page'),

    url(r'^remove_item$', 'data.views.remove_item'),
    url(r'^new_reservation$', 'data.views.make_reservation'),
    url(r'^delete_reservation$', 'data.views.delete_reservation'),
    url(r'^claim$', 'data.views.claim_listing'),
    url(r'^unclaim$', 'data.views.unclaim_listing'),
    #url(r'^email_seller$', 'data.views.email_seller'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),

    url(r'^login/password/', 'django.contrib.auth.views.login', name='login-password', ),
    url(r'^login/', 'mit.scripts_login', name='login', ),
    url(r'^no_cert$', 'data.views.no_cert_page'),
    url(r'^logout/', logout, name='logout', ),
)

data/models.py
from django.db import models
import smtplib
from email.mime.text import MIMEText
from googlevoice import Voice
from datetime import datetime
from site_specific_constants import SITE_ROOT, GEDDIT_GMAIL, GEDDIT_PASSWORD
import json

USERNAME_MAX_LENGTH = 25
PERSON_NAME_MAX_LENGTH = 25
PHONE_NUMBER_MAX_LENGTH = 20

LOCATION_NAME_MAX_LENGTH=100
class Location(models.Model):
    # The id field is automatically generated by Django
    # id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=LOCATION_NAME_MAX_LENGTH)
    longitude = models.DecimalField(verbose_name="Longitude",
                                    max_digits=20,
                                    decimal_places=17)
    latitude = models.DecimalField(verbose_name="Latitude",
                                   max_digits=20,
                                   decimal_places=17)
    
    def __unicode__(self):
        return unicode(self.name)
    
    class Meta:
        verbose_name = 'Location'
        verbose_name_plural = 'Locations'
    
    @staticmethod
    def create_location(locationName, lat, lng):
        l = Location(name=locationName,
                     longitude=lng,
                     latitude=lat)
        l.save()
        return l
    
    @staticmethod
    def get_location(name):
        return Location.objects.get(name=name)
    
class User(models.Model):
    # The id field is automatically generated by Django
    # id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=USERNAME_MAX_LENGTH, unique=True)
    first_name = models.CharField(max_length=PERSON_NAME_MAX_LENGTH)
    last_name = models.CharField(max_length=PERSON_NAME_MAX_LENGTH)
    email = models.EmailField()
    cell_phone = models.CharField(max_length=PHONE_NUMBER_MAX_LENGTH, blank=True, null=True)
    location = models.ForeignKey(Location, blank=True, null=True)
    email_notifications = models.BooleanField(default=True)
    sms_notifications = models.BooleanField(default=False)

    def __unicode__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    @staticmethod
    def create_user(username, first_name, last_name, email, cell_phone=None, location=None, \
            email_notifications=True, sms_notifications=False):
        u = User(username=username, first_name=first_name, \
                last_name=last_name, email=email, cell_phone=cell_phone,
                location=location, email_notifications=email_notifications,
                sms_notifications=sms_notifications)
        u.save()
        return u

    @staticmethod
    def get_user(username):
        return User.objects.get(username=username)

    @staticmethod
    def delete_user(user):
        user.delete()
    
    def send_email(self, message, subject):
        msg = MIMEText(message)
        msg['Subject'] = subject
        msg['From'] = GEDDIT_GMAIL
        msg['To'] = self.email

        s = smtplib.SMTP('localhost')
        s.sendmail(GEDDIT_GMAIL, [self.email], msg.as_string())
        s.quit()

    def send_sms(self, message):
        voice = Voice()
        voice.login(GEDDIT_GMAIL, GEDDIT_PASSWORD)
        voice.send_sms(self.cell_phone, message)

    def add_item(self, name, description, category, price, image=None):
        item = Item.create_item(self, name, description, category, price, image=image)

        # find reservations that match the item
        reservations = Reservation.get_matching_reservations(item)

        # figure out the users to be emailed and SMS-ed
        users = {}
        for reservation in reservations:
            if reservation.user.id in users:
                continue
            users[reservation.user.id] = reservation.user
        # email and SMS
        for uid in users:
            if users[uid].email_notifications:
                users[uid].send_email('An item has been posted that matches your reservation.\n' + \
                        'Check it out at ' + SITE_ROOT + 'buy?id=' + str(item.id), \
                        '[Geddit] matching reservation')
            if users[uid].sms_notifications:
                users[uid].send_sms('[Geddit] An item has been posted that matches your reservation.\n' + \
                        'Check it out at ' + SITE_ROOT + 'buy?id=' + str(item.id))

        return item

    def get_items(self):
        return Item.get_items(self)

    def remove_item(self, item):
        if item.seller_user != self:
            # error, you can't delete someone else's item
            return
        Item.delete_item(item)

    def add_claim(self, item):
        return Claim.create_claim(self, item)

    def remove_claim(self, item):
        claim = Claim.get_claim(item)
        if claim.buyer != self:
            raise AssertionError('Claim does not belong to you')
        Claim.delete_claim(claim)

    def get_claims(self):
        return Claim.get_claims(self)

    def add_reservation(self, search_query, max_price):
        return Reservation.create_reservation(self, search_query, max_price)

    def get_reservations(self):
        return Reservation.get_reservations(self)

    def remove_reservation(self, reservation):
        Reservation.delete_reservation(reservation)

CATEGORY_NAME_MAX_LENGTH = 100

class Category(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    name = models.CharField(max_length=CATEGORY_NAME_MAX_LENGTH)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    @staticmethod
    def create_category(name):
        c = Category(name=name)
        c.save()
        return c

    @staticmethod
    def get_category(name):
        return Category.objects.get(name=name)

    @staticmethod
    def delete_category(category):
        category.delete()

    @staticmethod
    def get_all_categories():
        return Category.objects.all().order_by('name')

ITEM_NAME_MAX_LENGTH = 100
DESCRIPTION_NAME_MAX_LENGTH = 1000

class Item(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    seller_user = models.ForeignKey(User)
    name = models.CharField(max_length=ITEM_NAME_MAX_LENGTH)
    description = models.CharField(max_length=DESCRIPTION_NAME_MAX_LENGTH)
    claimed = models.BooleanField()
    category = models.ForeignKey(Category)
    upload_time = models.DateTimeField(default=datetime.utcnow)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to="images/%Y/%m/%d/", blank=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    @staticmethod
    def create_item(seller_user, name, description, category, price, image=None):
        i = Item(seller_user=seller_user, name=name, description=description, \
                claimed=False, category=category, price=price, image=image)
        i.save()
        return i

    @staticmethod
    def get_item_by_id(id):
        return Item.objects.get(id=id)

    @staticmethod
    def get_items(seller_user):
        return Item.objects.filter(seller_user=seller_user)

    # deprecated
    @staticmethod
    def get_all_items():
        return Item.objects.all().filter(claimed=False).order_by('-upload_time')

    @staticmethod
    def get_filtered_items(category=None, search_query=None, id=None):
        items = Item.objects.all().filter(claimed=False)
        if category is not None:
            items = items.filter(category=category)
        if search_query is not None:
            for keyword in search_query.split():
                items = items.filter(name__icontains=keyword)
        if id is not None:
            items = items.filter(id=id)
        return items.order_by('-upload_time')

    @staticmethod
    def delete_item(item):
        if item.claimed:
            Claim.delete_claim(Claim.get_claim(item))
        item.delete()

    @staticmethod
    def get_item_location(item):
        pass
    
class Reservation(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()
    user = models.ForeignKey(User)
    search_query = models.CharField(max_length=DESCRIPTION_NAME_MAX_LENGTH)
    max_price = models.DecimalField(max_digits=8, decimal_places=2)
    timestamp = models.DateTimeField(default=datetime.utcnow)

    def __unicode__(self):
        return self.search_query

    class Meta:
        verbose_name = 'Reservation'
        verbose_name_plural = 'Reservations'

    @staticmethod
    def create_reservation(user, search_query, max_price):
        r = Reservation(user=user, search_query=search_query, max_price=max_price)
        r.save()
        return r

    @staticmethod
    def get_all_reservations():
        return Reservation.objects.all().order_by('-timestamp')

    @staticmethod
    def get_reservations(user):
        return Reservation.objects.filter(user=user).order_by('-timestamp')

    @staticmethod
    def get_reservation_by_id(id):
        return Reservation.objects.get(id=id)

    @staticmethod
    def get_matching_reservations(item):
        ''' returns the reservations that match the item '''
        matches = {}

        for keyword in item.name.split():
            reservations = Reservation.objects.filter( \
                    search_query__icontains=keyword, \
                    max_price__gte=item.price)
            for reservation in reservations:
                if reservation.id in matches:
                    continue
                matches[reservation.id] = reservation
        return matches.values()

    @staticmethod
    def delete_reservation(reservation):
        reservation.delete()

class Claim(models.Model):
    # Django will automatically generate this:
    # id = models.IntegerField()

templates/sell/reservations_table.html
{% if reservations %}
  <table id="sell-reservation-table">
    <thead>
      <tr class="table-column-titles-row">
        <td class="table-column-title sell-reservation-search-query-column">Item</td>
        <td class="table-column-title sell-reservation-max-price-column">Max Price</td>
      </tr>
    </thead>

    <tbody>
      {% for reservation in reservations %}
        {% cycle 'darkcolor' 'lightcolor' as rowcolor silent %}
        <tr class="table-row {{ rowcolor }}">
          <td class="sell-reservation-search-query-column">{{ reservation.search_query }}</td>
          <td class="sell-reservation-max-price-column">${{ reservation.max_price }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>People have not made any requests yet.</p>
{% endif %}

templates/sell/sell.html
{% extends "base/base.html" %}

{% block imports %}
  {{ block.super }}
  <style type="text/css">
    div#map_canvas {
      width: 300px;
      height: 300px;
      border: 1px solid black;
    }
  </style>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/sell/sell.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/sell/sell_form.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/sell/reservations_table.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/greyout.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/form.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/table.css" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/dashboard/divider.css" />
{% endblock %}

{% block js_extra_imports %}
<script
  type="text/javascript"
  src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBAomHvVoRCbc7MW7p0IpnJdSgGcFlbMUA&sensor=false">
</script>
<script
  type="text/javascript"
  src="{{ STATIC_URL }}js/google_maps.js">
</script>
<script src="{{ STATIC_URL }}js/greyout_dialog.js"
  type="text/javascript"
  charset="utf8"></script>
{% endblock %}

{% block content %}
  {% include 'sell/sell_form.html' %}
  <div id="new-listing-title"><h1>Create New Listing</h1>
    <div id="new-listing-button">
      <input type="button" class="button" value="New Listing" onclick="showGreyoutDialog();">
    </div>
  </div>
  
  <div class="divider"></div>
   
  <div id="sell-listings-title" class="table-title"><h1>Things People Have Requested</h1></div>
  {% include 'sell/reservations_table.html' %}
{% endblock %}

templates/sell/sell_form.html
<div class="greyout greyout-visible"></div>
<div id="new-listing" class="greyout-visible">
  <div class="form-title"><h1>New Listing</h1></div>
  <form enctype="multipart/form-data" action="{{ SITE_ROOT }}sell" method="post">
    {% csrf_token %}
    <div class="form-field">
      {{ form.name.errors }}
      <label for="id_{{ form.name.html_name }}" class="form-label">
        Item name:
      </label>
      {{ form.name }}
    </div>
    <div class="form-field">
      {{ form.description.errors }}
      <label for="id_{{ form.description.html_name }}" class="form-label">
        {{ form.description.label }}:
      </label>
      {{ form.description }}
    </div>
    <div class="form-field">
      {{ form.category.errors }}
      <label for="id_{{ form.category.html_name }}" class="form-label">
        {{ form.category.label }}:
      </label>
      {{ form.category }}
    </div>
    <div class="form-field">
      {{ form.price.errors }}
      <label for="id_{{ form.price.html_name }}" class="form-label">
        {{ form.price.label }}:
      </label>
      <div class="currency-field">
      <div class="dollar-sign">$</div>
      <input type="text" id="id_price" name="price" class="price-field">
      </div>
    </div>
    <div class="form-field">
      {{ form.image.errors }}
      <label for="id_{{ form.image.html_name }}" class="form-label">
        {{ form.image.label }}:
      </label>
      {{ form.image }}
    </div>
    <input id="sell-create-button" class="button" type="submit" value="Create Listing" />
    <input id="sell-cancel-button" type="button" class="button" value="Cancel" onclick="hideGreyoutDialog();">
  </form>
<!--
  {% if latitude and longitude %}
    <div id="map_canvas">
    </div>

    <div id="lat" style="display: none;">{{ latitude }}</div>
    <div id="lng" style="display: none;">{{ longitude }}</div>
  {% endif %}
-->
</div>